# Generated by Django 3.1.5 on 2021-01-07 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=8)),
                ('registration', models.CharField(max_length=15)),
                ('engine_number', models.CharField(max_length=30)),
                ('body_number', models.CharField(max_length=30)),
                ('chassis', models.CharField(max_length=30)),
                ('car_color', models.CharField(max_length=20)),
                ('mileage', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('car_type', models.CharField(max_length=20)),
                ('car_owner', models.CharField(max_length=60)),
                ('owner_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('consumable_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10, verbose_name='Ед.измер.')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_contract', models.FileField(blank=True, null=True, upload_to='', verbose_name='Контракт в пдф')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=9)),
                ('when_passport_issued', models.DateField()),
                ('whom_passport_issued', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10, verbose_name='Ед.измер.')),
                ('nexia3', models.FloatField(blank=True, null=True, verbose_name='Нексия 3')),
                ('cobalt', models.FloatField(blank=True, null=True, verbose_name='Кобальт')),
                ('malibu', models.FloatField(blank=True, null=True, verbose_name='Малибу')),
                ('nexia_sonc', models.FloatField(blank=True, null=True, verbose_name='Нексия Sonc')),
                ('damas', models.FloatField(blank=True, null=True, verbose_name='Дамас')),
                ('tiko', models.FloatField(blank=True, null=True, verbose_name='Тико')),
                ('matiz', models.FloatField(blank=True, null=True, verbose_name='Матиз')),
                ('matiz_best', models.FloatField(blank=True, null=True, verbose_name='Матиз Бест')),
                ('spark', models.FloatField(blank=True, null=True, verbose_name='Спарк')),
                ('nexia_dons', models.FloatField(blank=True, null=True, verbose_name='Нексия Донс')),
                ('lacceti', models.FloatField(blank=True, null=True, verbose_name='Лассети')),
                ('captiva', models.FloatField(blank=True, null=True, verbose_name='Каптива')),
                ('takuma', models.FloatField(blank=True, null=True, verbose_name='Такума')),
                ('epica', models.FloatField(blank=True, null=True, verbose_name='Эпика')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('nexia3', models.FloatField(blank=True, null=True, verbose_name='Нексия 3')),
                ('cobalt', models.FloatField(blank=True, null=True, verbose_name='Кобальт')),
                ('malibu', models.FloatField(blank=True, null=True, verbose_name='Малибу')),
                ('nexia_sonc', models.FloatField(blank=True, null=True, verbose_name='Нексия Sonc')),
                ('damas', models.FloatField(blank=True, null=True, verbose_name='Дамас')),
                ('tiko', models.FloatField(blank=True, null=True, verbose_name='Тико')),
                ('matiz', models.FloatField(blank=True, null=True, verbose_name='Матиз')),
                ('matiz_best', models.FloatField(blank=True, null=True, verbose_name='Матиз Бест')),
                ('spark', models.FloatField(blank=True, null=True, verbose_name='Спарк')),
                ('nexia_dons', models.FloatField(blank=True, null=True, verbose_name='Нексия Донс')),
                ('lacceti', models.FloatField(blank=True, null=True, verbose_name='Лассети')),
                ('captiva', models.FloatField(blank=True, null=True, verbose_name='Каптива')),
                ('takuma', models.FloatField(blank=True, null=True, verbose_name='Такума')),
                ('epica', models.FloatField(blank=True, null=True, verbose_name='Эпика')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Время создания')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='', verbose_name='Отчёт в пдф')),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото пасспорта')),
                ('registration_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото тех.пасспорта')),
                ('media_photo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Разные Фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car', to='makereport.car', verbose_name='Машина')),
                ('consumable', models.ManyToManyField(related_name='Расходники', to='makereport.Consumable', verbose_name='Расходники')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contract', to='makereport.contract', verbose_name='Контракт')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
                ('product', models.ManyToManyField(related_name='Детали', to='makereport.Product', verbose_name='Детали')),
                ('service', models.ManyToManyField(related_name='Услуги', to='makereport.Service', verbose_name='Услуги')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='makereport.customer'),
        ),
    ]
