# Generated by Django 3.1.5 on 2021-05-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='template_agreement',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='template_mixing',
        ),
    ]
