# Generated by Django 3.1.5 on 2021-03-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=20)),
                ('departure', models.CharField(max_length=20)),
                ('opr_ust', models.CharField(max_length=20)),
                ('opr_damage', models.CharField(max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='makereport.report', verbose_name='Репорт')),
            ],
        ),
    ]
