# Generated by Django 3.1.5 on 2021-05-07 20:34

from django.db import migrations, models
import makereport.models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0002_auto_20210508_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='template_agreement',
            field=models.FileField(blank=True, null=True, upload_to=makereport.models.handler_base_agreement, verbose_name='Шаблоны для догвора'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='template_mixing',
            field=models.FileField(blank=True, null=True, upload_to=makereport.models.handler_base_mixing, verbose_name='Шаблоны для заключения'),
        ),
    ]
