# Generated by Django 3.1.5 on 2021-03-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0002_report_pdf_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='key',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
