# Generated by Django 3.1.5 on 2021-01-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0002_auto_20210111_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='wear_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
