# Generated by Django 3.1.5 on 2021-03-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0003_auto_20210327_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
