# Generated by Django 3.1.5 on 2021-03-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0003_auto_20210308_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pdf_qr_code',
            new_name='pdf_qr_code_admin',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_qr_code_user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
