# Generated by Django 3.1.5 on 2021-05-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0003_auto_20210508_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(default=0, verbose_name='Введите сумму')),
            ],
            options={
                'verbose_name': 'Сумма',
                'verbose_name_plural': 'Сумма',
            },
        ),
    ]
