# Generated by Django 3.1.5 on 2021-01-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0003_report_wear_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
