# Generated by Django 3.1.5 on 2021-05-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0004_customsum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vid',
        ),
    ]
