# Generated by Django 3.1.5 on 2021-03-28 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0004_auto_20210328_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makereport.checks')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makereport.images')),
                ('o_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makereport.otherphotos')),
                ('pp_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makereport.passportphotos')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makereport.report')),
            ],
        ),
    ]
