# Generated by Django 3.1.5 on 2021-05-10 17:39

from django.db import migrations, models
import makereport.models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0005_remove_customer_vid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_agreement', models.FileField(blank=True, null=True, upload_to=makereport.models.handler_base_agreement, verbose_name='Шаблоны для догвора')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(blank=True, null=True, upload_to=makereport.models.handler_base, verbose_name='Шаблон для отчета')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateMixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_mixing', models.FileField(blank=True, null=True, upload_to=makereport.models.handler_base_mixing, verbose_name='Шаблоны для заключения')),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='template',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='template_agreement',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='template_mixing',
        ),
    ]
