# Generated by Django 3.1.5 on 2021-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0005_report_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Кобальт', 'Кобальт'), ('Спарк', 'Спарк')], max_length=30),
        ),
    ]
