# Generated by Django 3.1.5 on 2021-03-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0005_holdsimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdsimages',
            name='checks',
        ),
        migrations.AddField(
            model_name='holdsimages',
            name='checks',
            field=models.ManyToManyField(to='makereport.Checks'),
        ),
        migrations.RemoveField(
            model_name='holdsimages',
            name='image',
        ),
        migrations.AddField(
            model_name='holdsimages',
            name='image',
            field=models.ManyToManyField(to='makereport.Images'),
        ),
        migrations.RemoveField(
            model_name='holdsimages',
            name='o_images',
        ),
        migrations.AddField(
            model_name='holdsimages',
            name='o_images',
            field=models.ManyToManyField(to='makereport.OtherPhotos'),
        ),
        migrations.RemoveField(
            model_name='holdsimages',
            name='pp_photo',
        ),
        migrations.AddField(
            model_name='holdsimages',
            name='pp_photo',
            field=models.ManyToManyField(to='makereport.PassportPhotos'),
        ),
    ]
