# Generated by Django 3.1.5 on 2021-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0005_auto_20210112_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
