# Generated by Django 3.1.5 on 2021-01-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0006_auto_20210112_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='consumable_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='product_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='service_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
