# Generated by Django 3.1.5 on 2021-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0006_auto_20210328_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdsimages',
            name='checks_previous',
            field=models.ManyToManyField(related_name='check_previous', to='makereport.Checks'),
        ),
        migrations.AddField(
            model_name='holdsimages',
            name='image_previous',
            field=models.ManyToManyField(related_name='image_previous', to='makereport.Images'),
        ),
        migrations.AddField(
            model_name='holdsimages',
            name='o_images_previous',
            field=models.ManyToManyField(related_name='o_photo_previous', to='makereport.OtherPhotos'),
        ),
        migrations.AddField(
            model_name='holdsimages',
            name='pp_photo_previous',
            field=models.ManyToManyField(related_name='pp_photo_previous', to='makereport.PassportPhotos'),
        ),
    ]
