# Generated by Django 3.1.5 on 2021-05-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0006_auto_20210510_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateagreement',
            old_name='template_agreement',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='templatemixing',
            old_name='template_mixing',
            new_name='template',
        ),
    ]
