# Generated by Django 3.1.5 on 2021-01-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0007_auto_20210113_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='consumable_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='product_acc_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='product_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='service_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_report_cost',
            field=models.IntegerField(default=0),
        ),
    ]
