# Generated by Django 3.1.5 on 2021-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0008_auto_20210310_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Кобальт', 'Кобальт'), ('Спарк', 'Спарк'), ('Нексия3', 'Нексия3'), ('Малибу', 'Малибу'), ('Нексия Sonc', 'Нексия Sonc'), ('Дамас', 'Дамас'), ('Тико', 'Тико'), ('Матиз', 'Матиз'), ('Матиз Бест', 'Матиз Бест'), ('Нексия Donc', 'Нексия Donc'), ('Ласетти', 'Ласетти'), ('Каптива', 'Каптива'), ('Такума', 'Такума'), ('Эпика', 'Эпика')], max_length=30),
        ),
    ]
