# Generated by Django 3.1.5 on 2021-01-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0008_auto_20210113_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='total_report_cost',
            field=models.CharField(max_length=15),
        ),
    ]
