# Generated by Django 3.1.5 on 2021-03-12 05:15

from django.db import migrations, models
import makereport.models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0009_auto_20210310_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to=makereport.models.upload_path_handler, verbose_name='Шаблоны для пдф'),
        ),
    ]
