# Generated by Django 3.1.5 on 2021-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0010_auto_20210511_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, choices=[('Выберите Марку', 'Выберите Марку'), ('Кобальт', 'Кобальт'), ('Спарк', 'Спарк'), ('Нексия3', 'Нексия3'), ('Малибу', 'Малибу'), ('Нексия Sonc', 'Нексия Sonc'), ('Дамас', 'Дамас'), ('Тико', 'Тико'), ('Матиз', 'Матиз'), ('Матиз Бест', 'Матиз Бест'), ('Нексия Donc', 'Нексия Donc'), ('Ласетти', 'Ласетти'), ('Каптива', 'Каптива'), ('Такума', 'Такума'), ('Эпика', 'Эпика')], max_length=30, null=True),
        ),
    ]
