# Generated by Django 3.1.5 on 2021-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0010_myuser_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Лицензия')),
                ('guvonhnoma', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Гувохнома')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Сертификат')),
                ('insurance', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cтраховка')),
            ],
            options={
                'verbose_name': 'Фотографии для документа',
                'verbose_name_plural': 'Фотографии для документов',
            },
        ),
    ]
