# Generated by Django 3.1.5 on 2021-03-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0011_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand_text',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
