# Generated by Django 3.1.5 on 2021-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0011_auto_20210511_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='signed_by_boss',
            field=models.BooleanField(default=False),
        ),
    ]
