# Generated by Django 3.1.5 on 2021-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0011_report_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='media_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Разные Фото'),
        ),
    ]
