# Generated by Django 3.1.5 on 2021-02-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0012_auto_20210203_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='media_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contract', to='makereport.images', verbose_name='Фото'),
        ),
    ]
