# Generated by Django 3.1.5 on 2021-05-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0012_report_signed_by_boss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pdf_qr_code_admin',
            new_name='pdf_qr_code_company',
        ),
    ]
