# Generated by Django 3.1.5 on 2021-05-11 20:33

from django.db import migrations, models
import makereport.models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0013_auto_20210512_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(blank=True, null=True, upload_to=makereport.models.handler_base_additional, verbose_name='Шаблоны для дополнения')),
            ],
        ),
    ]
