# Generated by Django 3.1.5 on 2021-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0013_auto_20210320_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type_of_car',
            field=models.CharField(choices=[('Грузовой', 'Грузовой'), ('Легковой', 'Легковой')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
