# Generated by Django 3.1.5 on 2021-02-04 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0013_auto_20210204_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='media_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='makereport.images', verbose_name='Фото'),
        ),
    ]
