# Generated by Django 3.1.5 on 2021-05-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0014_templateadditional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='key',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
