# Generated by Django 3.1.5 on 2021-02-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0015_auto_20210204_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='media_photo',
            new_name='Images',
        ),
    ]
