# Generated by Django 3.1.5 on 2021-02-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0016_auto_20210206_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Images',
        ),
        migrations.AddField(
            model_name='images',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='makereport.report', verbose_name='Фото'),
        ),
    ]
