# Generated by Django 3.1.5 on 2021-02-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0017_auto_20210206_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportImages', to='makereport.report', verbose_name='Отчёт'),
        ),
        migrations.CreateModel(
            name='PassportPhotos',
            fields=[
                ('p_photo_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото пасспорта')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportPPhotos', to='makereport.report', verbose_name='Отчёт')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPhotos',
            fields=[
                ('o_photo_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото пасспорта')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportOPhotos', to='makereport.report', verbose_name='Отчёт')),
            ],
        ),
    ]
