# Generated by Django 3.1.5 on 2021-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0018_auto_20210215_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherphotos',
            name='photo',
        ),
        migrations.AddField(
            model_name='otherphotos',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото чеков'),
        ),
    ]
