# Generated by Django 3.1.5 on 2021-05-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0018_auto_20210516_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type_of_car',
            field=models.CharField(choices=[('Выберите тип машины', 'Выберите тип машины'), ('Грузовой', 'Грузовой'), ('Легковой', 'Легковой')], max_length=50),
        ),
    ]
