# Generated by Django 3.1.5 on 2021-05-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0019_auto_20210516_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='when_passport_issued',
            field=models.CharField(max_length=20),
        ),
    ]
