# Generated by Django 3.1.5 on 2021-05-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0020_auto_20210516_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
