# Generated by Django 3.1.5 on 2021-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0021_auto_20210517_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_report_additional',
            field=models.FileField(blank=True, null=True, upload_to='uploads_additional/%Y/%m/%d/', verbose_name='Дополнительный отчет в пдф'),
        ),
    ]
