# Generated by Django 3.1.5 on 2021-06-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0022_report_pdf_report_additional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginationModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=10, verbose_name='Количество документов на одной странице')),
                ('is_chosen', models.BooleanField(default=False, verbose_name='Активация для сайта')),
            ],
            options={
                'verbose_name': 'Документы на странице',
                'verbose_name_plural': 'Документы на странице',
            },
        ),
    ]
