# Generated by Django 3.1.5 on 2021-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0023_paginationmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
