# Generated by Django 3.1.5 on 2021-06-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0024_report_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enumeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_c', models.CharField(blank=True, max_length=50, null=True)),
                ('bank', models.CharField(blank=True, max_length=50, null=True)),
                ('MFO', models.CharField(blank=True, max_length=50, null=True)),
                ('INN', models.CharField(blank=True, max_length=50, null=True)),
                ('OKED', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_enumeration', to='makereport.report', verbose_name='Отчёт')),
            ],
        ),
    ]
