# Generated by Django 3.1.5 on 2021-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0025_enumeration'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type_report',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=0),
        ),
    ]
