# Generated by Django 3.1.5 on 2021-07-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0026_report_type_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=100, null=True)),
                ('movable_property', models.CharField(blank=True, max_length=100, null=True)),
                ('place_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('damage_auto', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('address_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_data', models.CharField(blank=True, max_length=100, null=True)),
                ('executor', models.CharField(blank=True, max_length=100, null=True)),
                ('requisite_executor', models.CharField(blank=True, max_length=100, null=True)),
                ('aim_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('appearance_cost', models.CharField(blank=True, max_length=100, null=True)),
                ('form_report', models.CharField(blank=True, max_length=100, null=True)),
                ('license_executor', models.CharField(blank=True, max_length=100, null=True)),
                ('legislative_contractual_limitations', models.CharField(blank=True, max_length=100, null=True)),
                ('main_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('data_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('data_creation_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_closing_base64', models.CharField(blank=True, max_length=1000000, null=True)),
                ('sign', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enumeration',
            name='pdf_report_enumeration',
            field=models.FileField(blank=True, null=True, upload_to='uploads_enumeration/%Y/%m/%d', verbose_name='Дополнительный отчет в пдф'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Отчёт в пдф'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pdf_report_additional',
            field=models.FileField(blank=True, null=True, upload_to='uploads_additional/%Y/%m/%d', verbose_name='Дополнительный отчет в пдф'),
        ),
        migrations.CreateModel(
            name='Disposable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_disposable', models.FileField(blank=True, null=True, upload_to='uploads_disposable/%Y/%m/%d', verbose_name='Одноразовый пдф')),
                ('pdf_created', models.FileField(blank=True, null=True, upload_to='uploads_created/%Y/%m/%d', verbose_name='Объединенный пдф')),
                ('holds_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makereport.holdsimages')),
            ],
        ),
    ]
