# Generated by Django 3.1.5 on 2021-07-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0027_auto_20210717_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closing',
            name='aim_mark',
        ),
        migrations.RemoveField(
            model_name='closing',
            name='appearance_cost',
        ),
        migrations.RemoveField(
            model_name='closing',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='closing',
            name='form_report',
        ),
        migrations.RemoveField(
            model_name='closing',
            name='legislative_contractual_limitations',
        ),
        migrations.RemoveField(
            model_name='closing',
            name='license_executor',
        ),
        migrations.RemoveField(
            model_name='closing',
            name='requisite_executor',
        ),
    ]
