# Generated by Django 3.1.5 on 2021-07-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0028_auto_20210718_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disposable',
        ),
    ]
