# Generated by Django 3.1.5 on 2021-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0029_delete_disposable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='pdf_contract',
        ),
        migrations.AddField(
            model_name='customer',
            name='type_customer',
            field=models.IntegerField(default=0),
        ),
    ]
