# Generated by Django 3.1.5 on 2021-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0032_auto_20210725_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='damage_auto',
            field=models.CharField(blank=True, default='Напишите сюда цену', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='closing',
            name='movable_property',
            field=models.CharField(blank=True, default='Движимое имущество легковой автомобиль НЕКСИЯ гос. номер 01 563 YBA 1997г/выпуска', max_length=100, null=True),
        ),
    ]
