# Generated by Django 3.1.5 on 2021-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0033_auto_20210726_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='damage_auto_desc',
            field=models.CharField(blank=True, default='Ущерб автотранспортного средства по состоянию ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='closing',
            name='movable_property',
            field=models.CharField(blank=True, default='Движимое имущество легковой автомобиль НЕКСИЯ гос. номер 01 563 YBA 1997г/выпуска', max_length=300, null=True),
        ),
    ]
