# Generated by Django 3.1.5 on 2021-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makereport', '0034_auto_20210727_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='whom_passport_issued',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
